title: TabFSBench
# author: GitHub User
# email: your-email@domain.com

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

# minima_reboot:
#   date_format: "%b %-d, %Y"
#   date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- github.md

# footer_icons:
# - username: arXiv
#   url: https://arxiv.org/abs/2501.18935
#   icon: arxiv-logomark-small.svg

# - username: Code
#   url: https://github.com/LAMDASZ-ML/TabFSBench
#   icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
